### ISSUE TITLE
Wrong colour in pulldown menu at hacs

### ISSUE THREAD

**Issue by chrislader** [78wesley/Home-Assistant-Darkish-Theme#4]
Looks like its white on white before pulldown selected, see screenshot.

Also looks like darkish is gone from hacs? Its the best theme ive ever seen.![image](https://user-images.githubusercontent.com/40333466/168411755-bad09625-b8d8-48cf-a17a-d63b7edab7bf.jpeg)

**Comment by 78wesley** [comment]
Fixed in commit https://github.com/78wesley/Home-Assistant-Darkish-Theme/commit/ea0733a90277f2475f3bf7c75bb5902c8fd6405d
